[build]
  base = "frontend"
  command = "npm run build"
  publish = "frontend/build"
  
[functions]
  directory = "netlify/functions"

[build.environment]
  REACT_APP_API_URL = "/.netlify/functions/server"