[build]
  base = "frontend"
  command = "CI=false npm run build"
  publish = "build"

[functions]
  directory = "netlify/functions"

[build.environment]
  REACT_APP_API_URL = "/.netlify/functions/server"